[tool.poetry]
name = "flaskapp"
version = "0.1.0"
description = "A basic Flask application"
authors = ["Edgar Daniel <acosta.edg@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"  # Especifica la versión de Python que estás usando
flask = "3.0.3"